CREATE TYPE "public"."project_status" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"client" text NOT NULL,
	"industry" text NOT NULL,
	"category" text NOT NULL,
	"short_description" text NOT NULL,
	"detailed_description" text DEFAULT '' NOT NULL,
	"client_need" text DEFAULT '' NOT NULL,
	"what_we_built" text DEFAULT '' NOT NULL,
	"customer_experience" text DEFAULT '' NOT NULL,
	"business_functionality" text DEFAULT '' NOT NULL,
	"services" text[] DEFAULT '{}'::text[] NOT NULL,
	"capabilities" text[] DEFAULT '{}'::text[] NOT NULL,
	"technologies" text[] DEFAULT '{}'::text[] NOT NULL,
	"website_url" text,
	"location" text,
	"preview_theme" text DEFAULT 'ink' NOT NULL,
	"preview_layout" text DEFAULT 'standard' NOT NULL,
	"hero_image" text,
	"preview_image" text,
	"gallery" text[] DEFAULT '{}'::text[] NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"homepage_visible" boolean DEFAULT false NOT NULL,
	"status" "project_status" DEFAULT 'published' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "projects_slug_unique" UNIQUE("slug")
);
