import type { LucideIcon } from "lucide-react"
import {
  BookOpen,
  Briefcase,
  Building2,
  Car,
  ChefHat,
  CreditCard,
  Film,
  Fuel,
  GraduationCap,
  HandCoins,
  HardHat,
  HeartPulse,
  Home,
  Landmark,
  LineChart,
  Plane,
  Rocket,
  ShoppingCart,
  Store,
  Trophy,
  Truck,
  UtensilsCrossed,
  Zap,
} from "lucide-react"
import type { BrandIconName } from "@/components/icons/brand-icons"

export type Industry = {
  slug: string
  name: string
  icon: LucideIcon
  brandIcon: BrandIconName
  group: "Financial" | "Commerce & Consumer" | "Industrial & Mobility" | "Public & Knowledge"
  tagline: string
  summary: string
  challenges: string[]
  solutions: string[]
  services: string[]
  /** Audience segments (by business stage/size) rather than industry sectors. */
  audience?: true
}

export const industries: Industry[] = [
  {
    slug: "finance",
    name: "Finance",
    icon: Landmark,
    brandIcon: "finance",
    group: "Financial",
    tagline: "Faster onboarding, tighter compliance, better client trust.",
    summary: "Secure, compliant digital tools for banks, advisers, lenders and wealth managers.",
    challenges: ["Heavy manual onboarding and document checks", "Strict security and audit expectations", "Client data spread across several systems", "Customers expecting self-service digital access"],
    solutions: ["Client portals with secure document exchange", "Automated onboarding and document processing", "Internal case management and reporting", "Integrations with existing financial platforms"],
    services: ["software-development", "ai-solutions", "automation-integrations"],
  },
  {
    slug: "mortgage-lending",
    name: "Mortgage & Lending",
    icon: HandCoins,
    brandIcon: "mortgage-lending",
    group: "Financial",
    tagline: "Faster decisions, clearer applications, fewer delays.",
    summary: "Digital application and underwriting tools for brokers, lenders and mortgage providers.",
    challenges: [
      "Manual document collection slows every application",
      "Affordability and eligibility rules change frequently",
      "Applicants and brokers chase status updates by phone",
      "Compliance and audit trails add administrative load",
      "Legacy systems don't connect to credit or valuation providers",
    ],
    solutions: [
      "Digital application and document upload portals",
      "Automated affordability and eligibility checks",
      "Status tracking for brokers and applicants",
      "Integrations with credit reference and valuation services",
    ],
    services: ["software-development", "automation-integrations", "ai-solutions"],
  },
  {
    slug: "banking-payments",
    name: "Banking & Payments",
    icon: CreditCard,
    brandIcon: "banking-payments",
    group: "Financial",
    tagline: "Secure, seamless payments customers actually trust.",
    summary: "Secure banking and payment experiences that connect legacy systems to modern rails.",
    challenges: [
      "Legacy core banking systems are costly to change",
      "Fraud and security risks on every transaction",
      "Customers expect instant, mobile-first experiences",
      "Integrating card networks, open banking and payment rails",
      "Strict regulatory and audit requirements",
    ],
    solutions: [
      "Secure customer-facing banking and payment apps",
      "Open banking and payment gateway integrations",
      "Fraud monitoring and secure-by-design engineering",
      "API layers that connect to legacy core systems",
    ],
    services: ["software-development", "mobile-app-development", "cybersecurity"],
  },
  {
    slug: "fintech",
    name: "FinTech",
    icon: LineChart,
    brandIcon: "fintech",
    group: "Financial",
    tagline: "Ship compliant financial products faster.",
    summary: "Product engineering for fintech teams building new financial products at pace.",
    challenges: [
      "Regulatory requirements slow product development",
      "Integrating banking, payment and identity providers",
      "Scaling infrastructure securely as users grow",
      "Building trust without an established brand",
      "Balancing rapid iteration with compliance-readiness",
    ],
    solutions: [
      "Secure-by-design product engineering",
      "Integrations with banking, payment and KYC providers",
      "Scalable cloud infrastructure built for growth",
      "Compliance-ready architecture and audit trails",
    ],
    services: ["saas-development", "software-development", "cybersecurity"],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    icon: HeartPulse,
    brandIcon: "healthcare",
    group: "Public & Knowledge",
    tagline: "Less admin, more time with patients.",
    summary: "Digital tools for clinics and care providers that reduce admin and improve patient experience.",
    challenges: ["Appointment admin consuming staff time", "Paper-based forms and records", "Sensitive data requiring careful handling", "Patients wanting simpler digital access"],
    solutions: ["Online booking and reminders", "Digital intake and consent forms", "Staff scheduling and internal systems", "Patient-facing apps and portals"],
    services: ["web-development", "mobile-app-development", "crm-business-systems"],
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    icon: Home,
    brandIcon: "real-estate",
    group: "Commerce & Consumer",
    tagline: "Fewer missed enquiries, faster lettings and sales.",
    summary: "Property platforms, portals and tools for agents, landlords and developers.",
    challenges: ["Listings and enquiries managed across portals and inboxes", "Manual viewing and tenancy administration", "Limited visibility of pipeline and performance", "Landlords and tenants expecting online updates"],
    solutions: ["Property listing websites and search", "CRM for applicants, vendors and landlords", "Tenant and landlord portals", "Automated reminders and document workflows"],
    services: ["web-development", "crm-business-systems", "automation-integrations"],
  },
  {
    slug: "ecommerce",
    name: "Retail, E-commerce & FMCG",
    icon: ShoppingCart,
    brandIcon: "retail-fmcg",
    group: "Commerce & Consumer",
    tagline: "Smoother checkout, fewer stockouts, more repeat orders.",
    summary: "Stores, supply chains and commerce systems for retailers, brands and FMCG suppliers.",
    challenges: [
      "Checkout drop-off and slow storefronts",
      "Stock and orders out of sync across channels",
      "Complex pricing, bundles or subscriptions",
      "Limited visibility across suppliers and distribution",
      "Growing customer service volume",
    ],
    solutions: ["Fast, conversion-focused storefronts", "Order, stock and fulfilment integrations", "B2B ordering portals", "AI-assisted customer support"],
    services: ["ecommerce", "automation-integrations", "ai-solutions"],
  },
  {
    slug: "food-beverage",
    name: "Food & Beverage",
    icon: ChefHat,
    brandIcon: "food-beverage",
    group: "Commerce & Consumer",
    tagline: "Consistent quality and service across every site.",
    summary: "Ordering, stock and operations systems for restaurants, cafés and multi-site food brands.",
    challenges: [
      "Stock and wastage tracked on paper or spreadsheets",
      "Orders managed separately across delivery platforms",
      "Inconsistent experience across multiple sites",
      "Staff scheduling and compliance record-keeping",
      "Limited visibility of sales performance across locations",
    ],
    solutions: [
      "Ordering and stock management systems",
      "Direct ordering to reduce delivery-platform fees",
      "Multi-site reporting dashboards",
      "Staff scheduling and compliance tools",
    ],
    services: ["software-development", "ecommerce", "data-analytics"],
  },
  {
    slug: "hospitality",
    name: "Travel & Hospitality",
    icon: UtensilsCrossed,
    brandIcon: "travel-hospitality",
    group: "Commerce & Consumer",
    tagline: "More direct bookings, fewer platform fees.",
    summary: "Booking, ordering and guest experiences for hotels, venues and travel brands.",
    challenges: ["Reliance on third-party booking platforms and their fees", "Manual rotas and stock management", "Inconsistent guest communication", "Disconnected systems across sites"],
    solutions: ["Direct booking and ordering", "Loyalty and guest apps", "Staff scheduling and operations tools", "Multi-site reporting dashboards"],
    services: ["mobile-app-development", "web-development", "crm-business-systems"],
  },
  {
    slug: "media-entertainment",
    name: "Media & Entertainment",
    icon: Film,
    brandIcon: "media-entertainment",
    group: "Commerce & Consumer",
    tagline: "Reach audiences faster across every channel.",
    summary: "Content, subscription and audience platforms for media and entertainment brands.",
    challenges: [
      "Content spread across multiple platforms and formats",
      "Manual rights and licensing tracking",
      "Audience data siloed from content decisions",
      "Subscription and payment management adds overhead",
      "Peak demand during releases strains infrastructure",
    ],
    solutions: [
      "Content management and multi-platform publishing",
      "Subscription and membership platforms",
      "Audience analytics and personalisation",
      "Scalable hosting for launch-day traffic",
    ],
    services: ["web-development", "cloud-devops", "data-analytics"],
  },
  {
    slug: "sports",
    name: "Sports",
    icon: Trophy,
    brandIcon: "sports",
    group: "Commerce & Consumer",
    tagline: "Deeper fan engagement, smoother matchday operations.",
    summary: "Ticketing, membership and fan engagement platforms for clubs, venues and sports brands.",
    challenges: [
      "Ticketing, membership and merchandise run on separate systems",
      "Fan engagement drops between matchdays",
      "Manual processes for memberships and renewals",
      "Limited data on fan behaviour and preferences",
      "Matchday operations rely on paper and radios",
    ],
    solutions: [
      "Ticketing and membership platforms",
      "Fan engagement apps and content",
      "Automated renewals and communications",
      "Fan analytics and matchday operations tools",
    ],
    services: ["mobile-app-development", "web-development", "data-analytics"],
  },
  {
    slug: "logistics",
    name: "Logistics",
    icon: Truck,
    brandIcon: "logistics",
    group: "Industrial & Mobility",
    tagline: "Real-time visibility from dispatch to delivery.",
    summary: "Systems that bring visibility and efficiency to deliveries, fleets and warehouses.",
    challenges: ["Tracking jobs and drivers with calls and messages", "Paper proof of delivery", "Customers asking 'where is my order?'", "Disconnected dispatch and invoicing"],
    solutions: ["Driver apps with proof of delivery", "Dispatch and job management systems", "Customer tracking portals", "Automated invoicing and reporting"],
    services: ["mobile-app-development", "software-development", "automation-integrations"],
  },
  {
    slug: "automotive",
    name: "Automotive",
    icon: Car,
    brandIcon: "automotive",
    group: "Industrial & Mobility",
    tagline: "Smoother sales, service and ownership experiences.",
    summary: "Booking, configuration and workshop systems for dealers, manufacturers and service centres.",
    challenges: [
      "Sales, service and parts run on disconnected systems",
      "Customers expect online booking and configuration",
      "Dealer and manufacturer data don't align",
      "Manual scheduling for servicing and repairs",
      "Limited visibility into inventory across sites",
    ],
    solutions: [
      "Online configurators and booking platforms",
      "Service and workshop scheduling systems",
      "Dealer and inventory management tools",
      "Integrations across sales, service and parts systems",
    ],
    services: ["web-development", "software-development", "automation-integrations"],
  },
  {
    slug: "aviation",
    name: "Aviation",
    icon: Plane,
    brandIcon: "aviation",
    group: "Industrial & Mobility",
    tagline: "Smoother journeys, fewer delays, happier passengers.",
    summary: "Booking, operations and passenger platforms for airlines and airport operators.",
    challenges: [
      "Booking, check-in and operations run on separate systems",
      "Disruption information reaches passengers too slowly",
      "Crew and ground staff scheduling is complex",
      "Loyalty and ancillary revenue tools don't connect",
      "Peak travel periods strain existing systems",
    ],
    solutions: [
      "Booking and self-service passenger platforms",
      "Real-time disruption and status notifications",
      "Crew and ground operations scheduling tools",
      "Loyalty programme and ancillary sales integrations",
    ],
    services: ["mobile-app-development", "web-development", "cloud-devops"],
  },
  {
    slug: "oil-gas",
    name: "Oil & Gas",
    icon: Fuel,
    brandIcon: "oil-gas",
    group: "Industrial & Mobility",
    tagline: "Safer operations, tighter compliance, less downtime.",
    summary: "Asset, inspection and compliance systems for operators and field service teams.",
    challenges: [
      "Asset and equipment data spread across sites",
      "Manual inspection and compliance reporting",
      "Safety-critical processes need reliable tracking",
      "Legacy control and monitoring systems",
      "Remote sites with limited connectivity",
    ],
    solutions: [
      "Asset and inspection management systems",
      "Digital compliance and safety reporting",
      "Field data capture apps for remote teams",
      "Dashboards for operational and safety metrics",
    ],
    services: ["software-development", "mobile-app-development", "data-analytics"],
  },
  {
    slug: "energy-utilities",
    name: "Energy & Utilities",
    icon: Zap,
    brandIcon: "energy-utilities",
    group: "Industrial & Mobility",
    tagline: "Reliable supply, informed customers, lower costs.",
    summary: "Customer, billing and field service systems for energy and utilities providers.",
    challenges: [
      "Usage and billing data spread across legacy systems",
      "Customers want self-service account and usage access",
      "Field engineers rely on paper job sheets",
      "Regulatory reporting takes significant manual effort",
      "Outage communication reaches customers too slowly",
    ],
    solutions: [
      "Customer self-service portals for billing and usage",
      "Field service apps for engineers",
      "Automated regulatory reporting",
      "Outage and status notifications",
    ],
    services: ["web-development", "mobile-app-development", "automation-integrations"],
  },
  {
    slug: "construction",
    name: "Construction",
    icon: HardHat,
    brandIcon: "construction",
    group: "Industrial & Mobility",
    tagline: "Fewer delays, clearer costs, safer sites.",
    summary: "Project, site and compliance systems for contractors, developers and site teams.",
    challenges: [
      "Project costs and timelines tracked across spreadsheets",
      "Site progress reported on paper or messaging apps",
      "Subcontractor and compliance documents scattered across email",
      "Limited real-time visibility for project managers",
      "Health and safety records kept manually",
    ],
    solutions: [
      "Project and site management systems",
      "Mobile apps for site reporting and photos",
      "Document and compliance tracking",
      "Live dashboards for costs and progress",
    ],
    services: ["software-development", "mobile-app-development", "data-analytics"],
  },
  {
    slug: "education",
    name: "E-Learning & Education",
    icon: GraduationCap,
    brandIcon: "education",
    group: "Public & Knowledge",
    tagline: "Better engagement, less enrolment and admin friction.",
    summary: "Learning platforms and administrative tools for schools, trainers and online course providers.",
    challenges: ["Course content scattered across tools", "Manual enrolment and payments", "Limited insight into learner progress", "Staff overloaded with admin"],
    solutions: ["Online learning platforms", "Enrolment, booking and payments", "Learner dashboards and progress tracking", "AI assistants for learner support"],
    services: ["web-development", "ai-solutions", "crm-business-systems"],
  },
  {
    slug: "publishing",
    name: "Publishing",
    icon: BookOpen,
    brandIcon: "publishing",
    group: "Public & Knowledge",
    tagline: "Reach readers faster across every platform.",
    summary: "Editorial, subscription and content platforms for publishers and media owners.",
    challenges: [
      "Content production spread across disconnected tools",
      "Subscription and paywall management is inflexible",
      "Manual tagging slows content discovery",
      "Readers expect a consistent experience across devices",
      "Advertising and subscription revenue reported separately",
    ],
    solutions: [
      "Content management and editorial workflow tools",
      "Subscription and paywall platforms",
      "AI-assisted tagging and content recommendations",
      "Unified reporting across revenue sources",
    ],
    services: ["web-development", "ai-solutions", "data-analytics"],
  },
  {
    slug: "professional-services",
    name: "Professional Services",
    icon: Briefcase,
    brandIcon: "digital-transformation",
    group: "Public & Knowledge",
    tagline: "Less admin, more billable, expert time.",
    summary: "Client portals and practice systems for firms that run on expertise and time.",
    challenges: ["Documents exchanged by email", "Time and matter tracking in spreadsheets", "Repetitive drafting and reviewing", "Clients wanting visibility of progress"],
    solutions: ["Secure client portals", "Practice and matter management", "AI-assisted document drafting and review", "Automated billing workflows"],
    services: ["software-development", "ai-solutions", "automation-integrations"],
    audience: true,
  },
  {
    slug: "startups",
    name: "Startups",
    icon: Rocket,
    brandIcon: "saas",
    group: "Commerce & Consumer",
    tagline: "From idea to a product customers will pay for.",
    summary: "From idea to a first product that real customers can use and pay for.",
    challenges: ["Turning an idea into a clear, buildable scope", "Limited budget and time to market", "Uncertainty about technology choices", "Needing something investors and customers can see"],
    solutions: ["Discovery and product definition", "Minimum viable products", "SaaS foundations: accounts, billing, admin", "Scalable architecture from day one"],
    services: ["software-development", "ui-ux-design", "web-development"],
    audience: true,
  },
  {
    slug: "smes",
    name: "SMEs",
    icon: Store,
    brandIcon: "crm",
    group: "Commerce & Consumer",
    tagline: "Practical technology that saves time, not budget.",
    summary: "Practical technology for small and medium-sized businesses that need to do more with less.",
    challenges: ["Too much time lost to admin", "Tools that don't work together", "Outdated website or systems", "No in-house technical team"],
    solutions: ["Professional websites that generate enquiries", "Custom tools replacing spreadsheets", "Automation between existing tools", "Ongoing support without hiring"],
    services: ["web-development", "automation-integrations", "maintenance-support"],
    audience: true,
  },
  {
    slug: "enterprise",
    name: "Enterprise",
    icon: Building2,
    brandIcon: "software-development",
    group: "Industrial & Mobility",
    tagline: "Modernise legacy systems without disrupting operations.",
    summary: "Complex platforms, integrations and modernisation for larger organisations.",
    challenges: ["Legacy systems that are hard to change", "Many teams, systems and stakeholders", "Security, governance and compliance needs", "Pressure to adopt AI responsibly"],
    solutions: ["Legacy modernisation programmes", "Enterprise integration", "Internal platforms and portals", "Governed AI solutions"],
    services: ["software-development", "cloud-devops", "ai-solutions"],
    audience: true,
  },
]

export function getIndustry(slug: string) {
  return industries.find((i) => i.slug === slug)
}
